### ISSUE TITLE
[BUG] Does not work out of the box, without any pillar

### ISSUE THREAD

**Issue by daks** [saltstack-formulas/backupninja-formula#5]
### Formula commit hash / release tag

using semantic-release version from #4 

### Versions reports (master & minion)

VM default-debian-10-3001-py3

### Pillar / config used

No pillar used

### Describe the bug

When running without any pillar, with only state `backupninja`

```
       Traceback (most recent call last):
         File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 400, in render_jinja_tmpl
           output = template.render(**decoded_context)
         File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
           return original_render(self, *args, **kwargs)
         File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
           return self.environment.handle_exception(exc_info, True)
         File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
           reraise(exc_type, exc_value, tb)
         File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
           raise value.with_traceback(tb)
         File "<template>", line 4, in top-level template code
         File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1073, in make_module
           return TemplateModule(self, self.new_context(vars, shared, locals))
         File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1152, in __init__
           body_stream = list(template.root_render_func(context))
         File "/tmp/kitchen/var/cache/salt/minion/files/base/backupninja/map.jinja", line 30, in top-level template code
           {% set backupninja = salt['defaults.merge'](defaults, backupninja) %}
         File "/usr/lib/python3/dist-packages/salt/modules/defaults.py", line 134, in merge
           return dictupdate.update(merged, src, merge_lists=merge_lists)
         File "/usr/lib/python3/dist-packages/salt/utils/dictupdate.py", line 45, in update
           raise TypeError("Cannot update using non-dict types in dictupdate.update()")
       TypeError: Cannot update using non-dict types in dictupdate.update()
       [DEBUG   ] Out: 
       /tmp/kitchen/var/cache/salt/minion/files/base/backupninja/map.jinja(30):
       ---
```

Adding a simple pillar
```
backupninja: {}
```

seems enough to be able to use this formula without customization.

### Expected behaviour

I expect this formula to run without any specific pillar and only the meta-state `backupninja`

### Attempts to fix the bug

Nothing at the moment

**Comment by daks** [comment]
After merge of #4 I think next step would be to switch to latest `map.jinja` implementation and it should resolve this bug.
